name: Deploy DocFX to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install DocFX
      - name: Install DocFX
        run: |
          sudo apt-get update
          wget https://github.com/dotnet/docfx/releases/download/v2.69.1/docfx.zip # Replace with the latest version
          unzip docfx.zip -d docfx
          sudo mv docfx/docfx /usr/local/bin/

      # Step 3: Build DocFX
      - name: Build DocFX project
        run: docfx build

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site/
